# Generated by Django 5.2.4 on 2025-07-18 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDRF', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('industry_sector', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('retail', 'Retail'), ('agriculture', 'Agriculture'), ('healthcare', 'Healthcare'), ('others', 'Others')], max_length=50)),
                ('business_legal_type', models.CharField(choices=[('sole', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company (LLC)'), ('corporation', 'Corporation')], max_length=50)),
                ('business_stage', models.CharField(choices=[('ideation', 'Ideation'), ('early', 'Early Stage'), ('growth', 'Growth'), ('mature', 'Mature')], max_length=50)),
                ('ownership_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ngo', 'Non-Profit / NGO')], max_length=50)),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('consulting', 'Consulting'), ('development', 'Development'), ('marketing', 'Marketing'), ('others', 'Others')], max_length=50)),
                ('service_description', models.TextField(default='Not provided.')),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='service_logos/')),
                ('registration_certificate', models.FileField(upload_to='certificates/')),
                ('tax_clearance_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sme_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
