# Generated by Django 5.2.4 on 2025-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDRF', '0004_smeprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
