# Generated by Django 5.2.4 on 2025-07-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDRF', '0005_alter_smeprofile_registration_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='SMEProfile',
        ),
    ]
